//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioPrueba.ServicioContadorPalabras {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioContadorPalabras.ServicioContadorSoap")]
    public interface ServicioContadorSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento texto del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContadorDePalabras", ReplyAction="*")]
        SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasResponse ContadorDePalabras(SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContadorDePalabras", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasResponse> ContadorDePalabrasAsync(SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContadorDePalabrasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContadorDePalabras", Namespace="http://tempuri.org/", Order=0)]
        public SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequestBody Body;
        
        public ContadorDePalabrasRequest() {
        }
        
        public ContadorDePalabrasRequest(SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ContadorDePalabrasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string texto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string palabra;
        
        public ContadorDePalabrasRequestBody() {
        }
        
        public ContadorDePalabrasRequestBody(string texto, string palabra) {
            this.texto = texto;
            this.palabra = palabra;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContadorDePalabrasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContadorDePalabrasResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasResponseBody Body;
        
        public ContadorDePalabrasResponse() {
        }
        
        public ContadorDePalabrasResponse(SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ContadorDePalabrasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ContadorDePalabrasResult;
        
        public ContadorDePalabrasResponseBody() {
        }
        
        public ContadorDePalabrasResponseBody(int ContadorDePalabrasResult) {
            this.ContadorDePalabrasResult = ContadorDePalabrasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioContadorSoapChannel : SitioPrueba.ServicioContadorPalabras.ServicioContadorSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioContadorSoapClient : System.ServiceModel.ClientBase<SitioPrueba.ServicioContadorPalabras.ServicioContadorSoap>, SitioPrueba.ServicioContadorPalabras.ServicioContadorSoap {
        
        public ServicioContadorSoapClient() {
        }
        
        public ServicioContadorSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioContadorSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioContadorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioContadorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasResponse SitioPrueba.ServicioContadorPalabras.ServicioContadorSoap.ContadorDePalabras(SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequest request) {
            return base.Channel.ContadorDePalabras(request);
        }
        
        public int ContadorDePalabras(string texto, string palabra) {
            SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequest inValue = new SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequest();
            inValue.Body = new SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequestBody();
            inValue.Body.texto = texto;
            inValue.Body.palabra = palabra;
            SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasResponse retVal = ((SitioPrueba.ServicioContadorPalabras.ServicioContadorSoap)(this)).ContadorDePalabras(inValue);
            return retVal.Body.ContadorDePalabrasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasResponse> SitioPrueba.ServicioContadorPalabras.ServicioContadorSoap.ContadorDePalabrasAsync(SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequest request) {
            return base.Channel.ContadorDePalabrasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasResponse> ContadorDePalabrasAsync(string texto, string palabra) {
            SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequest inValue = new SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequest();
            inValue.Body = new SitioPrueba.ServicioContadorPalabras.ContadorDePalabrasRequestBody();
            inValue.Body.texto = texto;
            inValue.Body.palabra = palabra;
            return ((SitioPrueba.ServicioContadorPalabras.ServicioContadorSoap)(this)).ContadorDePalabrasAsync(inValue);
        }
    }
}
